name: Deploy beta

on:
  push:
    branches:
      - master
    tags-ignore:
      - '**'

env:
  APIFY_BETA_COMPONENT_TAG: beta
  IMAGE_NAME: keboola-component
  KBC_APP_ID: apify.ex-google-maps-reviews-scraper
  KBC_VENDOR: apify
  KBC_DEVELOPER_PORTAL_USER: apify+ondro2

jobs:
  deploy:
    name: Deploy Application
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Build image
        run: docker build -t ${{ env.IMAGE_NAME }} .

      # - name: Run Tests
      #   run: docker run -e APIFY_TEST_TOKEN ${{ env.IMAGE_NAME }} npm test
      #   env:
      #     APIFY_TEST_TOKEN: ${{ secrets.APIFY_TEST_USER_API_TOKEN }}

      - name: Push image
        uses: odinuv/action-push-to-ecr@master
        with:
          vendor: ${{ env.KBC_VENDOR }}
          app_id: ${{ env.KBC_APP_ID }}
          username: ${{ env.KBC_DEVELOPER_PORTAL_USER }}
          password: ${{ secrets.KBC_DEVELOPERPORTAL_PASSWORD }}
          tag: ${{ env.APIFY_BETA_COMPONENT_TAG }}
          push_latest: true
          source_image: ${{ env.IMAGE_NAME }}
